---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: Install midnight commander package
    apt:
      name: mc
      state: present

