---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS) # roles koncepció miatt módosítottuk erre, az eredeti a site_before_role.yml néven mentettük.
    tags: always
    dnf:
      update_cache: yes
    changed_when: false #bootstrap.yml miatt
    when: ansible_distribution == "CentOS"

  - name: update repository index (Ubuntu) # roles koncepció miatt módosítottuk erre, az eredeti a site_before_role.yml néven mentettük.
    tags: always
    apt:
      update_cache: yes
    changed_when: false #bootstrap.yml miatt
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles: #roles (szabályok), tehát lényegében mostantól tasks helyett roles-t használunk.
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

    # web_servers      

- hosts: web_servers
  become: true
  roles:
    - web_servers

    # db_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

    # file_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

