- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start Apache service
  tags: apache,apache2,ubuntu
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

    # CentOS rész

- name: install httpd and php for CentOS servers
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

    #apache enable és service indítása CentOS alatt

- name: Start and enabled Httpd service
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

    #FÁJL MŰVELET ANSIBLE-LEL

    # admin e-mail cím csere
- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebady@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd #register egy változót definiál, bármit adhatunk pl. pizza

    # httpd újra indítása
- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed #a httpd az amit a register-nél adtunk

    #fájl másolás a /var/www/html/index.html-be
- name: copy default html files for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
