  # apache install mind a 2 rendszerre
- name: install apache and php packages
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package_name  }}"
      - "{{ php_package_name  }}"
    state: latest

  # apache indítás mind a 2 rendszerre
- name: Start and enabled Apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service  }}"
    state: started

    # admin e-mail cím csere
- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebady@somewhere.net
  when: ansible_distribution == "CentOS"
  register: apache #register egy változót definiál, előzör gyaknál httpd most apache, de bármit adhatunk pl. pizza

    # apache és httpd újra indítása mind a 2 rendszere
- name: restart httpd
  tags: apache,httpd
  service:
    name: "{{ apache_service  }}"
    state: restarted
  when: apache.changed #az apache az amit a register-nél adtunk

    #fájl másolás a /var/www/html/index.html-be
- name: copy default html files for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
