- name: install mariadb server package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: Start mariadb service
  tags: centos,db,mairadb
  service:
    name: mariadb
    state: started
  when: ansible_distribution == "CentOS"

- name: install mariadb server (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Start mariadb service
  tags: db,mariadb,ubuntu
  service:
    name: mariadb
    state: started
  when: ansible_distribution == "Ubuntu"
